CREATE SCHEMA IF NOT EXISTS `ims`;

USE `ims` ;

CREATE TABLE IF NOT EXISTS `ims`.`customers` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(40) DEFAULT NULL,
    `surname` VARCHAR(40) DEFAULT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `ims`.`items` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(60) DEFAULT NULL,
    `price` FLOAT DEFAULT 0.0,
    PRIMARY KEY (`id`)
);
